export enum Css {
  Row = 'exify-row',
  Grow = 'exify-grow',
  DontShrink = 'exify-dont-shrink',
  Align = 'exify-align',
  Center = 'exify-center',
  Spread = 'exify-spread',
  Pointer = 'exify-pointer',
  Border = 'exify-border',
  Shadow = 'exify-shadow',
  SpaceH = 'exify-space-h',
  SpaceV = 'exify-space-v',
  X05 = 'exify-x05',
  X15 = 'exify-x15',
  X2 = 'exify-x2',
  Logo = 'exify-logo',
  Loader = 'exify-loader',
  Icon = 'exify-icon',
  Button = 'exify-button',
  TextSm = 'exify-text--sm',
  TextMd = 'exify-text--md',
  Show = 'exify-show',
  FadeIn = 'exify-fade-in',
  Success = 'exify-success',
  PropertyList = 'exify-property-list',
  PropertyName = 'exify-property-name',
  PropertyValue = 'exify-property-value',
  Overlay = 'exify-overlay',
  OverlayBackground = 'exify-overlay-background',
  OverlayContent = 'exify-overlay-content',
  OverlaySettingsToggle = 'exify-overlay-settings-toggle',
  Settings = 'exify-settings',
  SettingsHeader = 'exify-settings-header',
  SettingsContent = 'exify-settings-content',
  SettingsFooter = 'exify-settings-footer',
  SettingsPropertyList = 'exify-settings-property-list',
  SettingsProperty = 'exify-settings-property',
}

export enum CheckboxIcon {
  On = 'check_box',
  Off = 'check_box_outline_blank',
}
